# Generated by Django 6.1.1 on 2026-09-24 09:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflows', '0003_workflowstage_task_stage_taskdependency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('TASK_STATUS_CHANGED', 'Task Status Changed'), ('TASK_COMPLETED', 'Task Completed'), ('APPROVAL_REQUESTED', 'Approval Requested'), ('APPROVAL_APPROVED', 'Approval Approved'), ('APPROVAL_REJECTED', 'Approval Rejected'), ('TASK_APPROACHING_DUE', 'Task Approaching Due Date'), ('TASK_OVERDUE', 'Task Overdue'), ('WORKFLOW_CREATED', 'Workflow Created'), ('WORKFLOW_COMPLETED', 'Workflow Completed'), ('WORKFLOW_ARCHIVED', 'Workflow Archived')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workflows.approval')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workflows.task')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workflows.workflow')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_2c3905_idx'), models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_4b40ec_idx')],
            },
        ),
    ]
