# Generated by Django 6.1.1 on 2026-09-24 03:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='workflows.workflow')),
            ],
            options={
                'db_table': 'workflow_stages',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='workflows.workflowstage'),
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_tasks', to='workflows.task')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='workflows.task')),
            ],
            options={
                'db_table': 'task_dependencies',
                'constraints': [models.UniqueConstraint(fields=('task', 'depends_on'), name='unique_task_dependency')],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.UniqueConstraint(fields=('workflow', 'order'), name='unique_workflow_stage_order'),
        ),
    ]
