# Generated by Django 6.1.1 on 2026-09-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DEACTIVATED', 'User Deactivated'), ('WORKFLOW_CREATED', 'Workflow Created'), ('WORKFLOW_UPDATED', 'Workflow Updated'), ('WORKFLOW_ARCHIVED', 'Workflow Archived'), ('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_COMPLETED', 'Task Completed'), ('TASK_CANCELLED', 'Task Cancelled'), ('TASK_DELETED', 'Task Deleted'), ('DEPENDENCY_CREATED', 'Dependency Created'), ('APPROVAL_REQUESTED', 'Approval Requested'), ('APPROVAL_APPROVED', 'Approval Approved'), ('APPROVAL_REJECTED', 'Approval Rejected')], max_length=40),
        ),
    ]
